spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/community_db
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  #  datasource:
  #    url: jdbc:h2:mem:authentication_example
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console

  security:
    user:
      password: 1

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: / # 메인페이지에서 swagger로 이동
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      - name: community
        packages-to-scan: com.han.springcommunity
